### ISSUE TITLE
作者您好，我在使用d_adapt.py 程序时出现了一些bug。

### ISSUE THREAD

**Issue by shishi-jie** [thuml/Transfer-Learning-Library#175]
Traceback (most recent call last):
  File "d_adapt.py", line 348, in <module>
    args=(args, args_cls, args_box),
  File "/home/shishijie/anaconda3/envs/detectron-na/lib/python3.6/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "d_adapt.py", line 277, in main
    train(model, logger, cfg, args, args_cls, args_box)
  File "d_adapt.py", line 163, in train
    bbox_adaptor.fit(data_loader_source, data_loader_target, data_loader_validation)
  File "/home/shishijie/shishijie_projects/domain_adapatation/Transfer-Learning-Library-master/examples/domain_adaptation/object_detection/d_adapt/bbox_adaptation.py", line 354, in fit
    x_s, labels_s = next(iter_source)
  File "/home/shishijie/shishijie_projects/domain_adapatation/Transfer-Learning-Library-master/examples/domain_adaptation/object_detection/d_adapt/tllib/utils/data.py", line 55, in __next__
    data = next(self.iter)
  File "/home/shishijie/anaconda3/envs/detectron-na/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/shishijie/anaconda3/envs/detectron-na/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1176, in _next_data
    raise StopIteration
StopIteration

我调了一天，我目前的看法是：a_adapt程序有四个训练阶段：源域预训练，类别适应，边界框适应，⽬标域伪标签训练。但是现在源域预训练没问题，我用源域的训练权重作为后续训练的预训练权重，10个epcho的类别适应训练也没问题，边界框适应训练出现了问题。

examples/domain_adaptation/object_detection/d_adapt/d_adapt.py 文件调用的bbox_adaptor.fit(data_loader_source, data_loader_target, data_loader_validation) 函数出现了问题，examples/domain_adaptation/object_detection/d_adapt/bbox_adaptation.py 文件中的 iter_source 拿不到标签数据，

（ps：自己的数据集和官方的voc2007和clipart数据集都是这样，我的训练命令：CUDA_VISIBLE_DEVICES=0  python d_adapt.py --config-file  config/retinanet_R_101_FPN_voc.yaml  -s VOC2007  ../datasets/VOC2007  -t Clipart ../datasets/clipart  --test Clipart ../datasets/clipart  --finetune  --bbox-refine   OUTPUT_DIR  logs/retinanet_R_101_FPN_voc/voc2clipart/phase2
）

劳烦作者费心给我这个废物一些指导

**Comment by thucbx99** [comment]
你可以先检查一下`len(data_loader_source)`是否为0，由此看一下相应的数据集是否正确生成了

**Comment by shishi-jie** [comment]
> 
# train the category adaptor
在这一步len(data_loader_source)不是0.

# train the bbox adaptor
在这一步len(data_loader_source)是0.

那下一步该怎么办呢（doge）

**Comment by thucbx99** [comment]
因为D-Adapt是一个迭代式的算法，category adaptor和bbox adaptor的输入都是在训练过程中生成的。
你的问题里data_loader_source是由BoundingBoxAdaptor的prepare_training_data函数生成的，那么接下来可以查看一下这个函数的参数proposal_list是不是空的，以及中间的筛选过程是不是把所有样本都筛出去了
