### ISSUE TITLE
torchvision should be upgrade

### ISSUE THREAD

**Issue by hetan697** [thuml/Transfer-Learning-Library#189]
**Describe the bug**
Like issue#114, the bug is not fixed yet.

**To Reproduce**
Example of cycada cannot be run successfully. It will raise exception.

**Additional context**
```
Traceback (most recent call last):
  File "/home/studio-lab-user/sagemaker-studiolab-notebooks/Transfer-Learning-Library/cycada.py", line 27, in <module>
    import tllib.vision.models.segmentation as models
  File "<frozen zipimport>", line 259, in load_module
  File "/home/studio-lab-user/.conda/envs/studiolab/lib/python3.9/site-packages/tllib-0.4-py3.9.egg/tllib/vision/models/segmentation/__init__.py", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/studio-lab-user/.conda/envs/studiolab/lib/python3.9/site-packages/tllib-0.4-py3.9.egg/tllib/vision/models/segmentation/deeplabv2.py", line 6, in <module>
ModuleNotFoundError: No module named 'torchvision.models.utils'
```

**Comment by thucbx99** [comment]
Thanks for pointing this out! Temporarily, you can git clone our code and modify the corresponding import directly. And we will fix it later.
