### ISSUE TITLE
docs 中 CDAN的例子给错

### ISSUE THREAD

**Issue by larry6799** [thuml/Transfer-Learning-Library#19]
docs: https://dalib.readthedocs.io/en/latest/dalib.adaptation.html#id4

原始例子：
```
>>> from dalib.modules.domain_discriminator import DomainDiscriminator
>>> num_classes = 2
>>> feature_dim = 1024
>>> batch_size = 10
>>> discriminator = DomainDiscriminator(in_feature=feature_dim, hidden_size=1024)
>>> loss = ConditionalDomainAdversarialLoss(discriminator, reduction='mean')
>>> # features from source domain and target domain
>>> f_s, f_t = torch.randn(batch_size, feature_dim), torch.randn(batch_size, feature_dim)
>>> # logits output from source domain adn target domain
>>> g_s, g_t = torch.randn(batch_size, num_classes), torch.randn(batch_size, num_classes)
>>> output = loss(g_s, f_s, g_t, f_t)
```

报错：
```
(sulimin) zb@zb-bit:~/zhangr/DANN$ python zr1.py
Traceback (most recent call last):
  File "zr1.py", line 13, in <module>
    output = loss(g_s, f_s, g_t, f_t)
  File "/home/zb/anaconda3/envs/sulimin/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zb/anaconda3/envs/sulimin/lib/python3.7/site-packages/dalib/adaptation/cdan.py", line 95, in forward
    d = self.domain_discriminator(h)
  File "/home/zb/anaconda3/envs/sulimin/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zb/anaconda3/envs/sulimin/lib/python3.7/site-packages/dalib/modules/domain_discriminator.py", line 37, in forward
    x = self.relu1(self.bn1(self.layer1(x)))
  File "/home/zb/anaconda3/envs/sulimin/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zb/anaconda3/envs/sulimin/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/zb/anaconda3/envs/sulimin/lib/python3.7/site-packages/torch/nn/functional.py", line 1674, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [20 x 2048], m2: [1024 x 1024] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:41
```

正确的CDAN例子:（修正了import和网络构建）
```
from dalib.modules.domain_discriminator import DomainDiscriminator
from dalib.adaptation.cdan import ConditionalDomainAdversarialLoss
import torch
num_classes = 2
feature_dim = 1024
batch_size = 10
discriminator = DomainDiscriminator(in_feature=feature_dim * num_classes, hidden_size=1024)
loss = ConditionalDomainAdversarialLoss(discriminator, reduction='mean')
# features from source domain and target domain
f_s, f_t = torch.randn(batch_size, feature_dim), torch.randn(batch_size, feature_dim)
# logits output from source domain adn target domain
g_s, g_t = torch.randn(batch_size, num_classes), torch.randn(batch_size, num_classes)
output = loss(g_s, f_s, g_t, f_t)
print(output)
```

**Comment by microhhh** [comment]
好的，感谢反馈。 Thanks for the feedback.
