### ISSUE TITLE
运行\examples\domain_adaptation\partial_domain_adaptation报错

### ISSUE THREAD

**Issue by zhy12345655** [thuml/Transfer-Learning-Library#258]
报错内容如下：
<class 'tllib.vision.datasets.partial.partial.<locals>.PartialDataset'>
Traceback (most recent call last):
  File "dann.py", line 261, in <module>
    main(args)
  File "dann.py", line 70, in main
    train_target_iter = ForeverDataIterator(train_target_loader)
  File "D:\soft\anaconda3\envs\pytorch_transfer_1.7.1\lib\site-packages\tllib-0.4-py3.8.egg\tllib\utils\data.py", line 45, in __init__
  File "D:\soft\anaconda3\envs\pytorch_transfer_1.7.1\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "D:\soft\anaconda3\envs\pytorch_transfer_1.7.1\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\soft\anaconda3\envs\pytorch_transfer_1.7.1\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "D:\soft\anaconda3\envs\pytorch_transfer_1.7.1\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\soft\anaconda3\envs\pytorch_transfer_1.7.1\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\soft\anaconda3\envs\pytorch_transfer_1.7.1\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\soft\anaconda3\envs\pytorch_transfer_1.7.1\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\soft\anaconda3\envs\pytorch_transfer_1.7.1\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'partial.<locals>.PartialDataset'
(pytorch_transfer_1.7.1) PS D:\code\Transfer-Learning-Library-master\examples\domain_adaptation\partial_domain_adaptation> Traceback (most recen
t call last):
  File "<string>", line 1, in <module>
  File "D:\soft\anaconda3\envs\pytorch_transfer_1.7.1\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\soft\anaconda3\envs\pytorch_transfer_1.7.1\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by thucbx99** [comment]
请问是直接运行我们的代码吗，还是做了一些修改之后，看样子像是加了Pytorch Lightning之类的框架之后跑的

**Comment by cjw-wx** [comment]
The same error appears, but it occurs in “\examples\domain_adaptation\image_regression\dd"and “\examples\domain_adaptation\image_regression\dann". I run them directly after git clone, without any change.

The details about error:
Traceback (most recent call last):
  File "dd.py", line 316, in <module>
    main(args)
  File "dd.py", line 74, in main
    train_source_iter = ForeverDataIterator(train_source_loader)
  File "E:\03_python_project\Transfer-Learning-Library\examples\domain_adaptation\image_regression\../../..\tllib\utils\data.py", line 45, in __init__
    self.iter = iter(self.data_loader)
  File "D:\06_anaconda\envs\Transfer_learning_lib\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "D:\06_anaconda\envs\Transfer_learning_lib\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\06_anaconda\envs\Transfer_learning_lib\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "D:\06_anaconda\envs\Transfer_learning_lib\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\06_anaconda\envs\Transfer_learning_lib\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\06_anaconda\envs\Transfer_learning_lib\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\06_anaconda\envs\Transfer_learning_lib\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\06_anaconda\envs\Transfer_learning_lib\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'DSprites.__init__.<locals>.<lambda>'
(Transfer_learning_lib) PS E:\03_python_project\Transfer-Learning-Library\examples\domain_adaptation\image_regression> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\06_anaconda\envs\Transfer_learning_lib\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\06_anaconda\envs\Transfer_learning_lib\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by cjw-wx** [comment]
This problem occurs when the code running in the windows platform, the default value of 'works' is 2, change it to 0 can solve above problem.
