### ISSUE TITLE
DANN example ValueError

### ISSUE THREAD

**Issue by codeyj373** [thuml/Transfer-Learning-Library#52]
Hello,
I just tried to rerun the DANN example using the command given in the README. But I got the following error message:
Traceback (most recent call last):
  File "dann.py", line 331, in <module>
    main(args)
  File "dann.py", line 136, in main
    lr_scheduler, epoch, args)
  File "dann.py", line 192, in train
    cls_loss = F.cross_entropy(y_s, labels_s)
  File "/home/yj373/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/functional.py", line 2468, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/yj373/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/functional.py", line 2262, in nll_loss
    .format(input.size(0), target.size(0)))
ValueError: Expected input batch_size (1568) to match target batch_size (32).

It seems like the shapes of y_s and label_s do not match with each other. How can I solve it? Thanks!

**Comment by codeyj373** [comment]
This issue happened when I run the code on the server. I tried to run it on my local machine, and the code works fine.
