### ISSUE TITLE
语义分割targets 的channel错误

### ISSUE THREAD

**Issue by zhou-rui1** [thuml/Transfer-Learning-Library#98]
Hi，对于语义分割的celoss，我总是得到如下错误，但是我不知道是哪一步导致了targets 的size为4，可以给些guidance吗，具体如下：
`Traceback (most recent call last):
  File "fda_copy.py", line 374, in <module>
    main(args)
  File "fda_copy.py", line 147, in main
    lr_scheduler, epoch, visualize if args.debug else None, args)
  File "fda_copy.py", line 224, in train
    loss_cls_s = criterion(pred_s, label_s)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py", line 1121, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py", line 2824, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: 1only batches of spatial targets supported (3D tensors) but got targets of size: : [2, 432, 778, 3]`

**Comment by tsingcbx99** [comment]
你好，我直接运行了一下fda的代码是没有问题的。没太理解你这里的意思，报错中的文件是fda_copy，这是你修改过的另一份文件？以及提到的target size为4，但是这个报错信息中没有和4相关的部分呀。可以先对比一下你修改的这份文件和原始的fda.py有什么区别~

**Comment by zhou-rui1** [comment]
hello,这个问题我已经解决啦，还想问下这个是不是没有伪标签的生成过程~

**Comment by tsingcbx99** [comment]
嗯是的
