### ISSUE TITLE
Error running example cycada (Object Type is not subscriptable)

### ISSUE THREAD

**Issue by LanariLorenzo** [thuml/Transfer-Learning-Library#99]
I'm trying to run cyada.sh on my dataset, divided in trainA and trainB for the two domains but i get this error:
```
Traceback (most recent call last):
  File "cycada.py", line 28, in <module>
    from common.utils.data import ForeverDataIterator
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/home/lorenzo/anaconda3/envs/cycada/lib/python3.8/site-packages/dalib-0.3-py3.8.egg/common/utils/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/home/lorenzo/anaconda3/envs/cycada/lib/python3.8/site-packages/dalib-0.3-py3.8.egg/common/utils/data.py", line 141, in <module>
TypeError: 'type' object is not subscriptable
Traceback (most recent call last):
  File "source_only.py", line 26, in <module>
    from common.utils.data import ForeverDataIterator
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/home/lorenzo/anaconda3/envs/cycada/lib/python3.8/site-packages/dalib-0.3-py3.8.egg/common/utils/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/home/lorenzo/anaconda3/envs/cycada/lib/python3.8/site-packages/dalib-0.3-py3.8.egg/common/utils/data.py", line 141, in <module>
TypeError: 'type' object is not subscriptable
```
I also tried to run dann.sh without modifying it and i get the same error.
Any idea on how to solve it? Thank you

**Comment by tsingcbx99** [comment]
I guess this is because **Linux** and **Windows** encode `.sh` files inconsistently. You can simply copy command from `cycada.sh`, then run it in the command line. Or maybe you are using Linux, do as follows:

- ` vi cycada.sh`

- `:set ff=unix`

- `:wq`

Then try runing again.

**Comment by LanariLorenzo** [comment]
Actually it was a problem caused by dependencies, i created a new conda environment and reinstalled from scratch and avoided the error.
